### ISSUE TITLE
Unable to parse multiple times when used with other parsing methods in micro

### ISSUE THREAD

**Issue by mjsisley** [timneutkens/urlencoded-body-parser#3]
https://github.com/zeit/micro/issues/384

**Comment by timneutkens** [comment]
You shouldn't parse multiple times, instead you should detect what the user is sending and parse based on that.

**Comment by mjsisley** [comment]
I had a use case where I needed to hash the entire raw body (either from `buffer(req).toString()` or `text(req)` and also needed the urlencoded arguments.

I ended up just using `buffer` and then just using `qs` directly, which is likely a better approach than a quick and dirty multiple parse.

The readme for micro states that parsing multiple times works for `text`,`buffer`, and `json` due to caching, so I wasn't sure if that was the intent or not for this library as well.

Thanks for the quick response.
